<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

/**
 * @property mixed model_id
 * @property mixed color
 * @property mixed measures
 * @property  mixed name
 * @property  mixed email
 * @property int status
 */
class Preventive extends Eloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'preventives';

    protected $fillable = [
        'email',
        'name',
        'measures',
        'color',
        'model_id',
        'status'
    ];

    public function get(string $string)
    {
        global $fillable;
        return $fillable[$string];
    }

    public function __get($key)
    {
        return parent::__get($key); // TODO: Change the autogenerated stub
    }
}
